[package]
name = "quicktree"
version = "0.1.0"
edition = "2021"
description = "A hashmap backed tree implementation"
license = "MIT"
keywords = ["tree", "ui", "dom"]

[dependencies]
hashbrown = "0.14"
thiserror = "1.0"

[dependencies.tinyvec]
version = "1.6"
features = ["alloc", "tinyvec_macros"]
